// Package private provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package private

// Defines values for SuccessProbe.
const (
	Ok SuccessProbe = "Ok"
)

// Valid indicates whether the value is a known member of the SuccessProbe enum.
func (e SuccessProbe) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Error Schema to define the error response
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// SuccessProbe Todo schema
type SuccessProbe string

// HealthyFailure Schema to define the error response
type HealthyFailure = Error

// HealthySuccess Todo schema
type HealthySuccess = SuccessProbe
