---
# Bonfire deployment configuration
# https://github.com/RedHatInsights/bonfire#app-config-overrides

# Defines where to fetch the file that defines application configs
# https://gitlab.cee.redhat.com/insights-platform/cicd-common
# https://gitlab.cee.redhat.com/insights-platform/cicd-common/-/blob/master/bonfire_configs/ephemeral_apps.yaml
#   See deprecation note here:
#     https://gitlab.cee.redhat.com/insights-platform/cicd-common/-/blob/master/bonfire_configs/ephemeral_apps.yaml#L1
# appsFile:
#   host: gitlab
#   repo: insights-platform/cicd-common
#   # path: bonfire_configs/ephemeral_apps.yaml
#   path: bonfire_configs/ephemeral_apps_deprecated.yaml

# (optional) define any apps locally. An app defined here with <name> will
# override config for app
# <name> in above fetched config.
apps:
  - name: idmsvc
    components:
      - name: backend
        # host: github
        # repo: idmsvc/idmsvc-backend
        host: local
        repo: ./
        path: deployments/clowder.yaml
        parameters:
          ENV_NAME: "ephemeral"
          IMAGE: ""
          IMAGE_TAG: ""
          # LOGGING_LEVEL: "info"
          APP_ACCEPT_X_RH_FAKE_IDENTITY: "true"

      - name: frontend
        host: github
        repo: podengo-project/idmsvc-frontend
        ref: main
        path: /deploy/frontend.yaml
        parameters:
          ENV_NAME: "ephemeral"
          IMAGE: "quay.io/cloudservices/idmsvc-frontend"
          # IMAGE_TAG: "b82077d"
